### ISSUE TITLE
Tulosten näyttäminen

### ISSUE THREAD

**Issue by SeveriN4** [jamktiko/huutisRepo#16]
Käyttäjänä haluan nähdä äänestystulokset, jotta saan äänestykseen ratkaisun

## Acceptance criteria

- [x] Frontend hakee äänestyksen tulokset DynamoDB:stä

- [x] Frontend visualisoi äänestystulokset haetun tiedon perusteella

- [x] Samassa huoneessa äänestäneet näkevät samat tulokset samaan aikaan

**Comment by TimoSaarela** [comment]
12h
