### ISSUE TITLE
Lambda fetchResults funktio

### ISSUE THREAD

**Issue by SeveriN4** [jamktiko/huutisRepo#39]
Kehittäjänä haluan, että funktio hakee DynamoDB:stä äänestystulosten datan frontendille visualisoitavaksi, jotta käyttäjä näkee tulokset

## Acceptance criteria

- [x] fetchaa äänestysvaihtoehdot tulosnäkymään

- [x] fetchaa äänestysvaihtoehdon äänimäärän tulosnäkymään

**Comment by AnttiR-hub** [comment]
2-4h
