### ISSUE TITLE
Huonokoodi number input

### ISSUE THREAD

**Issue by AnttiR-hub** [jamktiko/huutisRepo#60]
Käyttäjänä haluan, että huonekoodi kentän aktivoiminen avaa numeronäppäimistön automaatisesti mobiilissa

## Acceptance criteria

- [x] Mobiilissa huonekoodikentän aktivoiminen avaa numeronäppäimistön

- [x] Selaimessa koodin voi kirjoittaa eikä kenttään tule increment nappeja

**Comment by TimoSaarela** [comment]
15min
